services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsp-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
